version: '3.3'
services:
  service_geospatial_tracking:
      container_name: "geospatial-tracking"
      image: ${NAMESPACE}/${SERVICE}:${TAG}
      build:
        dockerfile: Dockerfile
        context: .
      volumes:
          - .:/geospatial_tracking/
      env_file: .env.geospatial.tracking
      environment:
           - TZ=Asia/Jakarta
           # elastic apm config
           - ELASTIC_APM_SERVICE_NAME=geospatial-tracking
           - ELASTIC_APM_LOG_LEVEL=DEBUG
           - ELASTIC_APM_ENVIRONMENT=development
           - ELASTIC_APM_SERVER_URL=http://51.79.155.191:8200
      ports:
          - "1112:1112"
      dns:
          - 8.8.8.8
          - 8.8.4.4
networks:
  default:
    external:
      name: backend-net